import { z } from 'zod';

export const batchUsageSchema = z.object({
  batchId: z.string(),
  consumedKg: z.number(),
});

export const beltProcessSchema = z.object({
  calendaringDate: z.string().optional(),
  calendaringMachine: z.string().optional(),
  greenBeltDate: z.string().optional(),
  greenBeltMachine: z.string().optional(),
  curingDate: z.string().optional(),
  curingMachine: z.string().optional(),
  inspectionDate: z.string().optional(),
  inspectionMachine: z.string().optional(),
  pidDate: z.string().optional(),
  packagingDate: z.string().optional(),
  dispatchDate: z.string().optional(),
});

export const createBeltSchema = z.object({
  beltNumber: z.string(),

  rating: z.string().optional(),
  fabricId: z.string().optional(),

  topCoverMm: z.number().optional(),
  bottomCoverMm: z.number().optional(),
  beltLengthM: z.number().optional(),
  beltWidthMm: z.number().optional(),
  edge: z.enum(['Cut', 'Moulded']).optional(),

  breakerPly: z.boolean().optional(),
  breakerPlyRemarks: z.string().optional(),
  carcassMm: z.number().optional(),
  coverGrade: z.string().optional(),

  orderNumber: z.string().optional(),
  buyerName: z.string().optional(),
  orderDate: z.string().optional(),
  deliveryDeadline: z.string().optional(),

  process: beltProcessSchema.optional(),

  coverBatchesUsed: z.array(batchUsageSchema).optional(),
  skimBatchesUsed: z.array(batchUsageSchema).optional(),

  status: z.enum(['Dispatched', 'In Production']).optional(),
  entryType: z.enum(['Manual', 'Auto']).optional(),
});

// Schema for the request body when creating a belt via API
export const createBeltRequestSchema = z.object({
  formData: z.object({
    beltNumber: z.string(),
    rating: z.string().optional(),
    beltStrength: z.union([z.number(), z.string()]).optional(),
    fabricType: z.string().optional(),
    topCover: z.union([z.number(), z.string()]).optional(),
    bottomCover: z.union([z.number(), z.string()]).optional(),
    beltLength: z.union([z.number(), z.string()]).optional(),
    beltWidth: z.union([z.number(), z.string()]).optional(),
    edge: z.string().optional(),
    carcass: z.union([z.number(), z.string()]).optional(),
    coverGrade: z.string().optional(),
    breakerPly: z.boolean().optional(),
    breakerPlyRemarks: z.string().optional(),
    orderNumber: z.string().optional(),
    buyerName: z.string().optional(),
    orderDate: z.union([z.date(), z.string()]).optional(),
    deliveryDeadline: z.union([z.date(), z.string()]).optional(),
    status: z.string().optional(),
    fabricSupplier: z.string().optional(),
    rollNumber: z.string().optional(),
    fabricConsumed: z.union([z.number(), z.string()]).optional(),
    coverCompoundType: z.string().optional(),
    skimCompoundType: z.string().optional(),
    coverCompoundConsumed: z.union([z.number(), z.string()]).optional(),
    skimCompoundConsumed: z.union([z.number(), z.string()]).optional(),
    dispatchDate: z.union([z.date(), z.string()]).optional(),
    packagingDate: z.union([z.date(), z.string()]).optional(),
    pdiDate: z.union([z.date(), z.string()]).optional(),
    inspectionDate: z.union([z.date(), z.string()]).optional(),
    inspectionStation: z.string().optional(),
    curingDate: z.union([z.date(), z.string()]).optional(),
    pressStation: z.string().optional(),
    greenBeltDate: z.union([z.date(), z.string()]).optional(),
    greenBeltStation: z.string().optional(),
    calendaringDate: z.union([z.date(), z.string()]).optional(),
    calendaringStation: z.string().optional(),
    coverCompoundProducedOn: z.union([z.date(), z.string()]).optional(),
    skimCompoundProducedOn: z.union([z.date(), z.string()]).optional(),
  }),
  coverConsumedKg: z.number(),
  skimConsumedKg: z.number(),
  coverCompoundCode: z.string().optional(),
  skimCompoundCode: z.string().optional(),
});

// Schema for updating a belt via API (compound consumption is optional)
export const updateBeltRequestSchema = z.object({
  formData: z.object({
    beltNumber: z.string().optional(),
    rating: z.string().optional(),
    beltStrength: z.union([z.number(), z.string()]).optional(),
    fabricType: z.string().optional(),
    topCover: z.union([z.number(), z.string()]).optional(),
    bottomCover: z.union([z.number(), z.string()]).optional(),
    beltLength: z.union([z.number(), z.string()]).optional(),
    beltWidth: z.union([z.number(), z.string()]).optional(),
    edge: z.string().optional(),
    carcass: z.union([z.number(), z.string()]).optional(),
    coverGrade: z.string().optional(),
    breakerPly: z.boolean().optional(),
    breakerPlyRemarks: z.string().optional(),
    orderNumber: z.string().optional(),
    buyerName: z.string().optional(),
    orderDate: z.union([z.date(), z.string()]).optional(),
    deliveryDeadline: z.union([z.date(), z.string()]).optional(),
    status: z.string().optional(),
    fabricSupplier: z.string().optional(),
    rollNumber: z.string().optional(),
    fabricConsumed: z.union([z.number(), z.string()]).optional(),
    coverCompoundType: z.string().optional(),
    skimCompoundType: z.string().optional(),
    coverCompoundConsumed: z.union([z.number(), z.string()]).optional(),
    skimCompoundConsumed: z.union([z.number(), z.string()]).optional(),
    dispatchDate: z.union([z.date(), z.string()]).optional(),
    packagingDate: z.union([z.date(), z.string()]).optional(),
    pdiDate: z.union([z.date(), z.string()]).optional(),
    inspectionDate: z.union([z.date(), z.string()]).optional(),
    inspectionStation: z.string().optional(),
    curingDate: z.union([z.date(), z.string()]).optional(),
    pressStation: z.string().optional(),
    greenBeltDate: z.union([z.date(), z.string()]).optional(),
    greenBeltStation: z.string().optional(),
    calendaringDate: z.union([z.date(), z.string()]).optional(),
    calendaringStation: z.string().optional(),
    coverCompoundProducedOn: z.union([z.date(), z.string()]).optional(),
    skimCompoundProducedOn: z.union([z.date(), z.string()]).optional(),
  }),
  coverConsumedKg: z.number().optional(),
  skimConsumedKg: z.number().optional(),
  coverCompoundCode: z.string().optional(),
  skimCompoundCode: z.string().optional(),
});
